### ISSUE TITLE
Ride EDIT screen is blank

### ISSUE THREAD

**Issue by NithyaMuthukumar** [robotframework/RIDE#1975]
![image](https://user-images.githubusercontent.com/34802395/62533581-a2423880-b864-11e9-8be7-d75199197a41.png)

**Comment by Nyral** [comment]
There should be errors/messages in RIDE>Tools>RIDE Log or in command line (if you opened it that way)

**Comment by Nyral** [comment]
Its been a month with no response. I guess we can now safely close it.

**Comment by ankitaverma1201** [comment]
I am facing the same issue. After creating a test case I could only see a blank screen in Edit tab.
I was using Robot framework 1.7.4b1. Then I tried updating it to 1.7.4b2. But still facing the same issue

**Comment by ankitaverma1201** [comment]
![RideEditblankScreen](https://user-images.githubusercontent.com/57214586/67936160-47b14200-fbf1-11e9-8c56-52e0e6dad276.PNG)

**Comment by HelioGuilherme66** [comment]
@ankitaverma1201 @NithyaMuthukumar That may be a screen refreshing problem. It will be OK if you select other Tabs, like Run or Text Edit, and then go back to the Cell Editor?
Please post here what is the version of wxPython.
Try to upgrade to wxPython 4.0.7 (released some days ago).

**Comment by ankitaverma1201** [comment]
@HelioGuilherme66 I tried doing the above process as suggested but still facing the same issue. 
I have installed  wxPython-4.0.7 version. 
Also have latest robot framework version.
What could be the issue? Have I missed something during installation?

**Comment by HelioGuilherme66** [comment]
@ankitaverma1201 Please paste here RIDE>Tools>RIDE Log after the issue occurred.

You can also install from current development version (`master` branch, just copy the Download link and `pip install -U the_link.zip`)

**Comment by ankitaverma1201** [comment]
@HelioGuilherme66 PFB the ride logs



20191101 11:19:23.437 [INFO]: Found Robot Framework version 3.1.2 from C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robot.

20191101 11:19:23.439 [INFO]: Started RIDE 1.7.4b1 using python version 3.8.0 with wx version 4.0.7.post1 in win32.

20191101 11:19:33.113 [ERROR]: **Error in listener: 'fixed font'**
While handling <robotide.publish.messages3.RideTreeSelection object at 0x0000017521C6B760>

Traceback (most recent call last):
'fixed font'
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\publish\publisher.py", line 103, in __call__
    self.listener(data)
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\__init__.py", line 123, in OnTreeItemSelected
    self._show_editor()
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\__init__.py", line 116, in _show_editor
    self._editor = self._create_editor()
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\__init__.py", line 120, in _create_editor
    return self._creator.editor_for(self, self._tab, self.tree)
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\editorcreator.py", line 53, in editor_for
    self._editor = self._create_editor(editor_panel, plugin, tree)
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\editorcreator.py", line 70, in _create_editor
    return self._create_new_editor(controller, editor_panel, plugin, tree)
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\editorcreator.py", line 87, in _create_new_editor
    return editor_class(plugin, editor_panel, controller, tree)
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\editors.py", line 80, in __init__
    self._populate()
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\macroeditors.py", line 33, in _populate
    self._create_kweditor()
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\macroeditors.py", line 37, in _create_kweditor
    self.kweditor = KeywordEditor(self, self.controller, self._tree)
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\kweditor.py", line 109, in __init__
    self._configure_grid()
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\kweditor.py", line 177, in _configure_grid
    self._set_fonts()
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\kweditor.py", line 181, in _set_fonts
    font_family = wx.FONTFAMILY_MODERN if self.settings['fixed font'] \
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\preferences\settings.py", line 322, in __getitem__
    value = self._config_obj[name]
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\preferences\configobj.py", line 616, in __getitem__
    val = dict.__getitem__(self, key)


20191101 11:19:37.403 [ERROR]: Error in listener: 'fixed font'
While handling <robotide.publish.messages3.RideNotebookTabChanged object at 0x0000017521C972B0>

Traceback (most recent call last):
'fixed font'
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\publish\publisher.py", line 103, in __call__
    self.listener(data)
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\__init__.py", line 143, in OnTabChanged
    self._show_editor()
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\__init__.py", line 116, in _show_editor
    self._editor = self._create_editor()
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\__init__.py", line 120, in _create_editor
    return self._creator.editor_for(self, self._tab, self.tree)
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\editorcreator.py", line 53, in editor_for
    self._editor = self._create_editor(editor_panel, plugin, tree)
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\editorcreator.py", line 70, in _create_editor
    return self._create_new_editor(controller, editor_panel, plugin, tree)
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\editorcreator.py", line 87, in _create_new_editor
    return editor_class(plugin, editor_panel, controller, tree)
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\editors.py", line 80, in __init__
    self._populate()
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\macroeditors.py", line 33, in _populate
    self._create_kweditor()
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\macroeditors.py", line 37, in _create_kweditor
    self.kweditor = KeywordEditor(self, self.controller, self._tree)
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\kweditor.py", line 109, in __init__
    self._configure_grid()
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\kweditor.py", line 177, in _configure_grid
    self._set_fonts()
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\kweditor.py", line 181, in _set_fonts
    font_family = wx.FONTFAMILY_MODERN if self.settings['fixed font'] \
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\preferences\settings.py", line 322, in __getitem__
    value = self._config_obj[name]
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\preferences\configobj.py", line 616, in __getitem__
    val = dict.__getitem__(self, key)


20191101 11:19:49.232 [ERROR]: Error in listener: 'fixed font'
While handling <robotide.publish.messages3.RideTreeSelection object at 0x0000017521C70D30>

Traceback (most recent call last):
'fixed font'
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\publish\publisher.py", line 103, in __call__
    self.listener(data)
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\__init__.py", line 127, in OnTreeItemSelected
    self._editor = self._create_editor()
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\__init__.py", line 120, in _create_editor
    return self._creator.editor_for(self, self._tab, self.tree)
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\editorcreator.py", line 53, in editor_for
    self._editor = self._create_editor(editor_panel, plugin, tree)
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\editorcreator.py", line 70, in _create_editor
    return self._create_new_editor(controller, editor_panel, plugin, tree)
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\editorcreator.py", line 87, in _create_new_editor
    return editor_class(plugin, editor_panel, controller, tree)
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\editors.py", line 80, in __init__
    self._populate()
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\macroeditors.py", line 33, in _populate
    self._create_kweditor()
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\macroeditors.py", line 37, in _create_kweditor
    self.kweditor = KeywordEditor(self, self.controller, self._tree)
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\kweditor.py", line 109, in __init__
    self._configure_grid()
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\kweditor.py", line 177, in _configure_grid
    self._set_fonts()
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\kweditor.py", line 181, in _set_fonts
    font_family = wx.FONTFAMILY_MODERN if self.settings['fixed font'] \
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\preferences\settings.py", line 322, in __getitem__
    value = self._config_obj[name]
  File "C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\preferences\configobj.py", line 616, in __getitem__
    val = dict.__getitem__(self, key)

**Comment by ankitaverma1201** [comment]
@HelioGuilherme66 PFB logs

20191101 11:26:39.000 [INFO]: Found Robot Framework version 3.1.2 from C:\Users\ac57486\AppData\Local\Programs\Python\Python38\lib\site-packages\robot.

20191101 11:26:39.001 [INFO]: Started RIDE 1.7.4b1 using python version 3.8.0 with wx version 4.0.7.post1 in win32.

20191101 11:26:51.555 [ERROR]: Error in listener: 'fixed font'
While handling <robotide.publish.messages3.RideTreeSelection object at 0x0000027B752E72E0>

Traceback (most recent call last):
'fixed font'
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\publish\publisher.py", line 103, in __call__
    self.listener(data)
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\__init__.py", line 127, in OnTreeItemSelected
    self._editor = self._create_editor()
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\__init__.py", line 120, in _create_editor
    return self._creator.editor_for(self, self._tab, self.tree)
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\editorcreator.py", line 53, in editor_for
    self._editor = self._create_editor(editor_panel, plugin, tree)
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\editorcreator.py", line 70, in _create_editor
    return self._create_new_editor(controller, editor_panel, plugin, tree)
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\editorcreator.py", line 87, in _create_new_editor
    return editor_class(plugin, editor_panel, controller, tree)
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\editors.py", line 80, in __init__
    self._populate()
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\macroeditors.py", line 33, in _populate
    self._create_kweditor()
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\macroeditors.py", line 37, in _create_kweditor
    self.kweditor = KeywordEditor(self, self.controller, self._tree)
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\kweditor.py", line 109, in __init__
    self._configure_grid()
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\kweditor.py", line 177, in _configure_grid
    self._set_fonts()
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\kweditor.py", line 181, in _set_fonts
    font_family = wx.FONTFAMILY_MODERN if self.settings['fixed font'] \
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\preferences\settings.py", line 322, in __getitem__
    value = self._config_obj[name]
  File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\preferences\configobj.py", line 616, in __getitem__
    val = dict.__getitem__(self, key)

**Comment by aimorari** [comment]
Hi guys, 
I facing the same issue :-(
Please see log below


20191101 11:58:07.715 [ERROR]: Error in listener: 'col size'
While handling <robotide.publish.messages3.RideNotebookTabChanged object at 0x000001E768B8C8B0>

Traceback (most recent call last):
'col size'
  File "C:\Users\andrei.moraru\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\publish\publisher.py", line 103, in __call__
    self.listener(data)
  File "C:\Users\andrei.moraru\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\__init__.py", line 146, in OnTabChanged
    self._show_editor()
  File "C:\Users\andrei.moraru\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\__init__.py", line 119, in _show_editor
    self._editor = self._create_editor()
  File "C:\Users\andrei.moraru\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\__init__.py", line 123, in _create_editor
    return self._creator.editor_for(self, self._tab, self.tree)
  File "C:\Users\andrei.moraru\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\editorcreator.py", line 53, in editor_for
    self._editor = self._create_editor(editor_panel, plugin, tree)
  File "C:\Users\andrei.moraru\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\editorcreator.py", line 70, in _create_editor
    return self._create_new_editor(controller, editor_panel, plugin, tree)
  File "C:\Users\andrei.moraru\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\editorcreator.py", line 87, in _create_new_editor
    return editor_class(plugin, editor_panel, controller, tree)
  File "C:\Users\andrei.moraru\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\editors.py", line 80, in __init__
    self._populate()
  File "C:\Users\andrei.moraru\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\macroeditors.py", line 33, in _populate
    self._create_kweditor()
  File "C:\Users\andrei.moraru\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\macroeditors.py", line 37, in _create_kweditor
    self.kweditor = KeywordEditor(self, self.controller, self._tree)
  File "C:\Users\andrei.moraru\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\kweditor.py", line 102, in __init__
    self._configure_grid()
  File "C:\Users\andrei.moraru\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\editor\kweditor.py", line 135, in _configure_grid
    self.SetDefaultColSize(self.settings['col size'],
  File "C:\Users\andrei.moraru\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\preferences\settings.py", line 322, in __getitem__
    value = self._config_obj[name]
  File "C:\Users\andrei.moraru\AppData\Local\Programs\Python\Python38\lib\site-packages\robotide\preferences\configobj.py", line 616, in __getitem__
    val = dict.__getitem__(self, key)

**Comment by HelioGuilherme66** [comment]
@ankitaverma1201 @aimorari Please install RIDE version 1.7.4b2 (or the development version as I mentioned). I believe that the problem is fixed in newer versions. If not then keep us informed. Thanks.

**Comment by ankitaverma1201** [comment]
@HelioGuilherme66 I have tried using RIDE version 1.7.4b2 but faced the same issue. can you please guide me how to download the development version.

**Comment by HelioGuilherme66** [comment]
@ankitaverma1201 The command is (run on a command window as administrator):
```
pip install -U https://github.com/robotframework/RIDE/archive/master.zip
```

**Comment by stepTest** [comment]
![image](https://user-images.githubusercontent.com/57478975/68369787-164af000-0176-11ea-8ced-237e0393b447.png)
 i tried to run this command but still having the same issue.
pip install -U https://github.com/robotframework/RIDE/archive/master.zip

![image](https://user-images.githubusercontent.com/57478975/68369889-4b574280-0176-11ea-8dc5-16dbadd7880d.png)

**Comment by ankitaverma1201** [comment]
@HelioGuilherme66 this solution is not working as well as mentioned by @stepTest

**Comment by HelioGuilherme66** [comment]
@stepTest @ankitaverma1201 Finally identified the root cause. It is because of Python 3.8.
See [this comment](https://github.com/robotframework/RIDE/issues/2039#issuecomment-550074600).

We are not testing yet on Python 3.8. That will only happen on next RIDE version 2.0.

**Comment by stepTest** [comment]
@HelioGuilherme66 , @ankitaverma1201 
Noted and thanks for the update.

**Comment by ankitaverma1201** [comment]
@HelioGuilherme66 Thank you

**Comment by HelioGuilherme66** [comment]
Fixed by #2128
