### ISSUE TITLE
ride.py won't run.

### ISSUE THREAD

**Issue by jeonghunjeong** [robotframework/RIDE#1985]
When running ride.py, the following is provided and will not be executed.

-----
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\application\application.py", line 59, in OnInit
    self._plugin_loader.enable_plugins()
  File "C:\Python27\lib\site-packages\robotide\application\pluginloader.py", line 43, in enable_plugins
    p.enable_on_startup()
  File "C:\Python27\lib\site-packages\robotide\application\pluginconnector.py", line 52, in enable_on_startup
    self.enable()
  File "C:\Python27\lib\site-packages\robotide\application\pluginconnector.py", line 57, in enable
    self._plugin.enable()
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 162, in enable
    self._build_ui()
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 558, in _build_ui
    self._build_notebook_tab()
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 734, in _build_notebook_tab
    self.out = self._create_output_textctrl()
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 769, in _create_output_textctrl
    font = self._create_font()
  File "C:\Python27\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py", line 789, in _create_font
    font=wx.SystemSettings.GetFont(wx.SYS_ANSI_FIXED_FONT)
wx._core.wxAssertionError: C++ assertion "wxFontEnumerator::IsValidFacename(font.GetFaceName())" failed at ..\..\src\msw\settings.cpp(301) in wxSystemSettingsNative::GetFont():
OnInit returned false, exiting...
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed
Error in sys.exitfunc:
Traceback (most recent call last):
  File "C:\Python27\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

-----
The installed packages and versions are as follows.

Package             Version
----------------- -------
numpy               1.16.5
Pillow                 6.1.0
pip                    19.2.3
Pygments           2.4.2
PyPubSub           3.3.0
pywin32              224
robotframework         3.1.2
robotframework-ride  1.7.3.1
robotframeworklexer  1.1
setuptools                  20.10.1
six                               1.12.0
wxPython                    4.0.4

**Comment by Nyral** [comment]
What operating system are you using?

**Comment by jeonghunjeong** [comment]
> What operating system are you using?

I'm using the Windows 10 home version.

**Comment by Nyral** [comment]
Please execute this in python and tell me what it returns.
`wx.SystemSettings.GetFont(wx.SYS_ANSI_FIXED_FONT).GetFaceName()`

It seems that system font is seen as invalid for some reason. I also notice that you're using an older RIDE release. In the latest release we changed how fonts are set, could you try it out?

**Comment by jeonghunjeong** [comment]
> This issue has been reported before. See #1828.
> 
> It seems that `wx.SYS_ANSI_FIXED_FONT` does not return a valid font on your system.
> 
> You have 3 possible solutions:
> 
> * switch to python 3
> * upgrade to latest RIDE version
> * modify RIDE code and replace `wx.SYS_ANSI_FIXED_FONT` with `wx.SYS_SYSTEM_FONT` (location is mentioned in trace)
> 
> Pick whichever suits you more.

Resolved with reference to the SYS ANSI_FIXED_FONT fix in # 1985. Thank you.

**Comment by Duanxh2018** [comment]
solution：
find file testrunnerplugin.py
in XXXX\python\lib\site-packages\robotide\contrib\testrunner\testrunnerplugin.py
find 789 row：
change font=wx.SystemSettings.GetFont(wx.SYS_ANSI_VAR_FONT) to
font=wx.SystemSettings.GetFont(wx.SYS_ANSI_FIXED_FONT)
if still not use, u can change to
font=wx.SystemSettings.GetFont(wx.SYS_SYSTEM_FONT)
