### ISSUE TITLE
Issue with 'Run Keywords' in Teardown Section: Subsequent Keywords Misplaced upon Reopening RIDE

### ISSUE THREAD

**Issue by didiyou** [robotframework/RIDE#2778]
When using the "Run Keywords" command within the Teardown section of a test to execute multiple keywords, I encounter an issue where, after saving and closing RIDE, reopening the suite results in only the first keyword remaining in the Teardown section. The subsequent keywords are incorrectly moved to the test case section.

Steps to reproduce:
1. Create a test case in RIDE.
2. In the Teardown section, use "Run Keywords" to specify multiple keywords (e.g., "Keyword1" AND "Keyword2" AND "Keyword3").
3. Save the test case and close RIDE.
4. Reopen RIDE and navigate to the same test case.

Expected behavior: All keywords specified after "Run Keywords" should remain in the Teardown section.

Actual behavior: Only the first keyword ("Keyword1") remains in the Teardown section, while the rest ("Keyword2", "Keyword3", ...) are moved to the main content of the test case.

This issue affects the organization of the test cases and how the Teardown is executed. I would appreciate a resolution or any guidance on this matter. Thank you.

**Comment by HelioGuilherme66** [comment]
@didiyou You did not mention the version of RIDE and Python. This bug is fixed in current development version, v2.1dev41 (if your Python is greater or equal to 3.8).

I attach a test suite created with the workflow you described:
[test_teardown_format.robot.txt](https://github.com/robotframework/RIDE/files/15443925/test_teardown_format.robot.txt)

**Comment by Yanwei0914** [comment]
Where is the RIDE version?

**Comment by didiyou** [comment]
> @didiyou You did not mention the version of RIDE and Python. This bug is fixed in current development version, v2.1dev41 (if your Python is greater or equal to 3.8).
> 
> I attach a test suite created with the workflow you described: [test_teardown_format.robot.txt](https://github.com/robotframework/RIDE/files/15443925/test_teardown_format.robot.txt)
> 
> In the [Changelog](https://github.com/robotframework/RIDE/blob/master/CHANGELOG.adoc#fixed), you can see the fix entry: `Fixed wrong continuation of long chains of keywords in Setups, Teardowns or Documentation`
my version is:
![企业微信截图_1717038378278](https://github.com/robotframework/RIDE/assets/23073456/f3eba707-2e86-4a6c-9ec3-69e9f24885b2)
![企业微信截图_17170383954247](https://github.com/robotframework/RIDE/assets/23073456/3b942999-de2a-4fb3-b2aa-b173fa7b0d32)
but this issue is still exists...

**Comment by HelioGuilherme66** [comment]
@didiyou You can install the development version using the pip command you can see in the Code page here, or in the Release Notes in the Help menu.

**Comment by didiyou** [comment]
> @didiyou You can install the development version using the pip command you can see in the Code page here, or in the Release Notes in the Help menu.

Yeah, this dev version has fixed the issue. By the way, any idea when the official release is coming out?

**Comment by HelioGuilherme66** [comment]
>any idea when the official release is coming out?
Next week I will release first Beta.

**Comment by didiyou** [comment]
> > any idea when the official release is coming out?
> 
> Next week I will release first Beta.

During use, I discovered several points that can easily cause the software to crash

**Comment by didiyou** [comment]
> > any idea when the official release is coming out?
> 
> Next week I will release first Beta.

During use, I discovered several points that can easily cause the software to crash
1. Click here, and the software will crash
![企业微信截图_17175800497198](https://github.com/robotframework/RIDE/assets/23073456/caf62623-72ee-4699-8123-6ae1c705ac27)
2. When I enter a newline in a cell

additionally, so after I upgraded to this development version, my Windows computer keeps blue screening and restarting. Do you think this could be because of the update?

**Comment by HelioGuilherme66** [comment]
@didiyou 
>Click here, and the software will crash
This is new for me, I'll see If I can reproduce. (need to know your Python and wxPython versions).

>When I enter a newline in a cell
This may be related with a problem in Windows and I made a fix for this. You need to edit your settings.cfg, and set to False in the [Grid] section this setting:
```
# filter newlines: When enabled, newlines are not shown as \n in the cells. On Windows this may cause a lock.
filter newlines = False
```

This could also be the fix for your first problem.

I don't know the cause of blue screens in your Windows machine. Could be many things, maybe related with graphic drivers, or low memory, if wxPython is doing some intense graphics use.
See if the fix I mention, solves the problems, and if the blue screens stop appearing we can say that there was some high probability of they being caused by RIDE/wxPython/Python.

**Comment by didiyou** [comment]
> @didiyou
> 
> > Click here, and the software will crash
> > This is new for me, I'll see If I can reproduce. (need to know your Python and wxPython versions).
> 
> > When I enter a newline in a cell
> > This may be related with a problem in Windows and I made a fix for this. You need to edit your settings.cfg, and set to False in the [Grid] section this setting:
> 
> ```
> # filter newlines: When enabled, newlines are not shown as \n in the cells. On Windows this may cause a lock.
> filter newlines = False
> ```
> 
> This could also be the fix for your first problem.
> 
> I don't know the cause of blue screens in your Windows machine. Could be many things, maybe related with graphic drivers, or low memory, if wxPython is doing some intense graphics use. See if the fix I mention, solves the problems, and if the blue screens stop appearing we can say that there was some high probability of they being caused by RIDE/wxPython/Python.

By the way，this development version of the editor changes my formatting. In the run keyword if ... else statement, it modifies the format of the else part, like this:
![企业微信截图_17175863676798](https://github.com/robotframework/RIDE/assets/23073456/67f8914f-98f6-49e9-b2e9-db25a134e64f)

**Comment by HelioGuilherme66** [comment]
@didiyou 
>By the way，this development version of the editor changes my formatting. In the run keyword if ... else statement, it modifies the format of the else part, like this:

Yes, it does. See #2790

(good that users find and report problems. better have them duplicated, then not have them)

**Comment by didiyou** [comment]
> @didiyou
> 
> > By the way，this development version of the editor changes my formatting. In the run keyword if ... else statement, it modifies the format of the else part, like this:
> 
> Yes, it does. See #2790
> 
> (good that users find and report problems. better have them duplicated, than not have them)

Is there a better solution? Do you mean all conditional branches need to be written on one line?

**Comment by HelioGuilherme66** [comment]
>Is there a better solution? Do you mean all conditional branches need to be written on one line?

No, that is a workaround until the bug is fixed. Just be aware of the problem and how to avoid breaking the test.

**Comment by didiyou** [comment]
> > Is there a better solution? Do you mean all conditional branches need to be written on one line?
> 
> No, that is a workaround until the bug is fixed. Just be aware of the problem and how to avoid breaking the test.

So will the beta version next week fix this error？

**Comment by HelioGuilherme66** [comment]
Please try current development version, v2.1dev49.

**Comment by yushiwolele** [comment]
@HelioGuilherme66 Will this be fixed in version 2.0.8.1? Our team works in an internal network environment, and we are currently using version 2.0.8.1. Upgrading to a newer version would be very costly for our team.
